export const foods = [
    {
        id: "1",
        name: "cake",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "2",
        name: "cake",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "3",
        name: "cake",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "4",
        name: "cake",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "5",
        name: "cake",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "6",
        name: "chocolate",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "7",
        name: "chocolate",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "8",
        name: "chocolate",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "9",
        name: "chocolate",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "10",
        name: "chocolate",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "11",
        name: "milk",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "12",
        name: "milk",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "13",
        name: "milk",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "14",
        name: "milk",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "15",
        name: "milk",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "16",
        name: "pasta",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "17",
        name: "pasta",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "18",
        name: "pasta",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "19",
        name: "pasta",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "20",
        name: "pasta",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "21",
        name: "pasta",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "22",
        name: "pasta",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "23",
        name: "pizza",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "24",
        name: "pizza",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "25",
        name: "pizza",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "26",
        name: "pizza",
        title: "",
        desc: "",
        img: "",
    },

    {
        id: "27",
        name: "pizza",
        title: "",
        desc: "",
        img: "",
    },

    {
        id: "28",
        name: "pizza",
        title: "",
        desc: "",
        img: "",
    },

    {
        id: "29",
        name: "pizza",
        title: "",
        desc: "",
        img: "",
    },
    {
        id: "30",
        name: "pizza",
        title: "",
        desc: "",
        img: "",
    },
  
]

// module.exports = foods;